version: '3'

services:
  app:
    build: .
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    # networks:
    #   - app-network

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:  
  #     - mongo:/data/db
  #   networks:
  #     - app-network

volumes:
  # mongo:
  node_modules:

# networks:
#   app-network: