version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://localhost:27017/mydatabase 
    networks:
      - app-network
    volumes:
      - app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:  
      - app:/data/db  

    

volumes:
  mongo:
  app:
  node_modules:

networks:
  app-network: