export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
};

export type HttpStatusCode = 
    | typeof HTTP_STATUS.OK
    | typeof HTTP_STATUS.CREATED
    | typeof HTTP_STATUS.ACCEPTED
    | typeof HTTP_STATUS.NO_CONTENT
    | typeof HTTP_STATUS.BAD_REQUEST
    | typeof HTTP_STATUS.UNAUTHORIZED
    | typeof HTTP_STATUS.FORBIDDEN
    | typeof HTTP_STATUS.NOT_FOUND
    | typeof HTTP_STATUS.METHOD_NOT_ALLOWED
    | typeof HTTP_STATUS.CONFLICT
    | typeof HTTP_STATUS.UNPROCESSABLE_ENTITY
    | typeof HTTP_STATUS.TOO_MANY_REQUESTS
    | typeof HTTP_STATUS.INTERNAL_SERVER_ERROR;
